# Generated by Django 5.2.5 on 2025-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_dispositivo_consumo_remove_dispositivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='watts',
            field=models.FloatField(default=0, help_text='Consumo nominal en watts'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='categoria',
            field=models.CharField(choices=[('Sensor', 'Sensor'), ('Actuador', 'Actuador'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='consumo',
            field=models.FloatField(help_text='Consumo en kWh'),
        ),
    ]
